# -*- coding: utf-8 -*-
"""promptScrape.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ib85DxSE_NHg5wQvcYP1ShOZN-Ff8702
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from tqdm import tqdm

def get_prompts(page_number):
  url = f"https://library.easyprompt.xyz/prompt/{page_number}"
  result = requests.get(url)
  doc = BeautifulSoup(result.text,"html.parser")
  best_prompt = doc.find('div', class_="utils_response__b5jEi")
  base_prompt = doc.find('p', class_="text-xl font-display")
  views = doc.find_all('p', class_="text-center text-gray-600 text-sm")[1]
  return base_prompt.text, best_prompt.text, views.text

prompt_df = pd.DataFrame(columns=["base_prompt","improved_prompt","views"])

for i in tqdm(range(1,344)):
  try:
    base_prompt, best_prompt,views = get_prompts(i)
    prompt_df = pd.concat([prompt_df, pd.DataFrame({"base_prompt": [base_prompt], "improved_prompt": [best_prompt], "views":[views]})], ignore_index=True)
    time.sleep(1)
  except:
    print("error fetching page",i)

prompt_df.to_csv("prompt.csv",index=False)